name: Update Gists

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0" # Runs every week at Sunday midnight

jobs:
  update_gists:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Update README
        run: node gists.js
        env:
          CI: true

      - name: Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git diff --cached --quiet || git commit -m "Update README with latest gists"
          git push origin main
